config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
    root "home#index"
    get '/user/subcategory/:id', to: "home#subcategory"
    get '/user/products/:id', to: "home#product"
    get '/user/cart/:id',to:"home#cart"
    post '/addcart',to:"home#addcart"
    get '/profile',to:"home#profile"
  
  namespace :supplier do
    resources :products
    resources :category
  end
 
  namespace :admins do
    get 'order/index'
    resources :users
    resources :order
    resources :categorylists
    resources :subcategories
  end

get 'listitem/new'
get 'listitem/index'
post 'listitems' ,to: "listitem#create"
post 'listitems/:id/inc' ,to: "listitem#add_quantity", as: "listitem_inc"
post 'listitems/:id/dec' ,to: "listitem#reduce_quantity", as: "listitem_dec"
delete 'listitems/:id' ,to: "listitem#destroy",as:"listitem_rem"


get '/carts/' ,to: "cart#show", as: "cart"
delete '/carts/:id' ,to: "cart#destroy" ,as: "cart_destroy"
resources :carts
# resources :products
resources :order
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products ,dependent: :delete_all
  has_many :list_items ,dependent: :delete_all
  has_many :products ,through: :list_items,dependent: :delete_all

  def sub_total
    sum=0
    self.list_items.each do |i|
      sum+= i.total_price
    end
    return sum
  end
  def sub_total1
    sum=[]
    j=1
    k=0
    self.list_items.each do |i|
      while(k<j)
        sum[k]= i.total_price
        k+=1
      end
      j+=1
    end
    return sum
  end
end

app/models/categorylist.rb
class Categorylist < ApplicationRecord
     mount_uploader :cover, CoverUploader
     has_many :subcategories, class_name: "Categorylist",foreign_key: "category_id",dependent: :destroy
     belongs_to :category, class_name: "Categorylist", optional: true
     has_many :products ,dependent: :delete_all
     validates :name, presence: true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :imageble,polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :cover, CoverUploader
    has_many :list_items ,dependent: :delete_all
    belongs_to :categorylist
    
    validates :name, presence: true
    validates :detail, presence: true
    validates :price, presence: true ,numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :cover, CoverUploader
  has_many :list_items ,dependent: :delete_all
  has_one :cart ,dependent: :destroy
  has_many :orders ,dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
  
    protected
    
      def configure_permitted_parameters
        # devise_parameter_sanitizer.permit(:sign_in, keys: [:user_name,:password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:user_name,:user_type,:phone,:pincode,:city,:address,:email])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name,:user_name,:phone,:pincode,:city,:address,:email,:cover]) 
      end
 

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include UserHelper
  def show
    @cart = find_user(current_user.id).cart
  end

  def destroy
    Cart.find(params[:id]).destroy
    redirect_to carts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UserHelper
  

  def index
    case
    when current_user.user_type =="user"
       @categories = Categorylist.all
       @product1 = Product.all
       sub1(@categories)
       
    when current_user.user_type =="admin"
      redirect_to "/admins/categorylists"
    when current_user.user_type =="supplier"
      redirect_to "/supplier/products"
    
      
    end
  end

  def subcategory
    @subcategory  = categorylist(params[:id]).subcategories
  end

  def product 
    @product  = categorylist(params[:id]).products
  end

  def profile
    @user = User.find(current_user.id)
  end

  def addcart

    @Addcart = ListItem.new
    @Addcart.save
    redirect_to root_url
  
  end

  def cart
    @CartItems = find_user(params[:id]).carts
    @CartItems.each do |cartItem|  
      @listitem = find_cart(cartItem.id).list_items
    end
  end

  
end

app/controllers/listitem_controller.rb
class ListitemController < ApplicationController
  include UserHelper
  before_action :listitem , only: [:add_quantity,:reduce_quantity,:destroy]
  
  def listitem
    ListItem.find(params[:id])
  end

  def create
    chosen_product = Product.find(params[:product_id])
    if find_user(current_user.id).cart == nil
      current_cart = Cart.create(user_id:current_user.id)

    else  
      current_cart =  find_user(current_user.id).cart
    end
    
    if find_cart(current_cart.id).products.include?(chosen_product)
      @list_item = find_cart(current_cart.id).list_items.find_by(product_id: chosen_product)
      @list_item.quantity += 1
    else
      @list_item = ListItem.new(cart_id:current_cart.id, product_id:chosen_product.id, user_id:current_user.id)
    end
    
    @list_item.save
    redirect_to cart_path
  end


  def add_quantity
    @list_item =  listitem
    @list_item.quantity += 1
    @list_item.save
    redirect_to cart_path
  end
  

  def reduce_quantity
    @list_item = listitem
    if @list_item.quantity > 1
      @list_item.quantity -= 1
    end
    @list_item.save
    redirect_to cart_path
  end
  def destroy
    @list_item = listitem
    @list_item.destroy
    redirect_to cart_path
  end 
  # private
  #   def list_item_params
  #     params.require(:list_item).permit(:quantity,:product_id, :cart_id)
  #   end

  
  
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  include UserHelper
  def index
    @products = []
    i=0
    n=1
    @orders = find_user(current_user.id).orders
        @orders.each do |order|
      while(i<n)
        @products[i] = Product.find(order.product_id)
        i+=1
      end
      n+=1
    end
  end


  def show
    @order = find_user(params[:id]).orders
  end

  def new
    @order = Order.new
  end

  def create
    current_cart =  find_user(current_user.id).cart
    find_cart(current_cart.id).products.each do |item|
        @order = Order.new(status:params["status"],user_id:current_user.id,product_id:item.id)
        @order.save
        
      end
      find_cart(current_cart.id).destroy
    
    redirect_to root_path
  end

end

app/helpers/admin/show_helper.rb
module Admin::ShowHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listitem_helper.rb
module ListitemHelper
    
    def listitem
        ListItem.find(params[:id])
    end

    def user_find
        User.find(current_user.id)
    end
    
    def cart_find
        Cart.find(current_cart.id)
    end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/user_helper.rb
module UserHelper

    def find_user(arg)
        User.find(arg)
    end

    def find_cart(arg)
        Cart.find(arg)
    end

    def categorylist(arg)
        Categorylist.find(arg)
    end

    def sub1(arg)
      j=0
      k=1 
      @subcategory = []
      arg.each do |i|
        if i.category_id != nil
          while(j<k)
            @subcategory[j] = i  
            j+=1
          end
          k+=1
        end
      end
    end
end

app/views/cart/show.html.erb
<%if @cart==nil%>
 <div class="container">
      <%=image_tag "missingcart.png" %>
          <h1>Missing Cart items? <a href="/">click here</a></h1>
 </div>
<%else%>

<section class="h-100 h-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12">
        <div class="card card-registration card-registration-2" style="border-radius: 15px;">
          <div class="card-body p-0">
            <div class="row g-0">
              <div class="col-lg-8">
                <div class="p-5">
                  <div class="d-flex justify-content-between align-items-center mb-5">
                    <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                    <h6 class="mb-0 text-muted"><%=@cart.list_items.count%> items</h6>
                  </div>
                  <% @cart.list_items.each do |list_items| %>

                  <hr class="my-4">

                  <div class="row mb-4 d-flex justify-content-between align-items-center">
                    <div class="col-md-2 col-lg-2 col-xl-2">
                      <%= image_tag(list_items.product.cover.url,class:"img-fluid rounded-3" , height: 150, width: 150) if list_items.product.cover%>
                    </div>
                    <div class="col-md-3 col-lg-3 col-xl-3">
                      <h6 class="text-muted"><%= list_items.product.name %></</h6>
                      <%# <h6 class="text-black mb-0">Cotton T-shirt</h6> %>
                    </div>
                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                      <button class="btn btn-link px-2">
                            <%= link_to "Inc", listitem_inc_path(id: list_items.id), method: :post %>

                      </button>

                      <input id="form1" min="0" name="quantity" value="<%= list_items.quantity%>" type="number"
                        class="form-control form-control-sm" />

                      <button class="btn btn-link px-2">
                        <%= link_to "Dec", listitem_dec_path(id:list_items.id), method: :post %>
                      </button>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                      <h6 class="mb-0"><%= list_items.product.price %></h6>
                    </div>
                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                        <%= link_to "Del",listitem_rem_path(id:list_items.id),method: :delete%>
                      
                    </div>
                  </div>          
                <% end  %>

                  <hr class="my-4">
                  <div class="pt-5">
                    <h6 class="mb-0"><a href="/" class="text-body"><i class="bi bi-arrow-left-circle"></i> Back to shop</a></h6>
                          <h6 class="mb-0"> <%= link_to "Empty cart", cart_destroy_path(@cart.id),method: :delete, data: {confirm: "Are you sure?"}%></h6>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 bg-grey">
                <div class="p-5">
                  <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
                  <hr class="my-4">
                    <%j=1%>
                    <%k=0%>
                    <%@cart.list_items.each do |i|%>

                  <div class="d-flex justify-content-between mb-4">
                    <h5 class="text-uppercase">items <%=j%></h5>
                    <h5><%= number_to_currency(@cart.sub_total1[k]) %><h5>
                  </div>
                  <%j+=1%>
                  <%k+=1%>
                    <%end%>

                  <hr class="my-4">

                  <div class="d-flex justify-content-between mb-5">
                    <h5 class="text-uppercase">Total price</h5>
                    <h5><%= number_to_currency(@cart.sub_total) %></h5>
                  </div>

                  <button type="button" class="btn btn-dark btn-block btn-lg text-white"
                    data-mdb-ripple-color="dark"><%= link_to "Place Order", new_order_path %></button>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
 <%end%>

app/views/listitem/new.html.erb
<h1>Listitem#new</h1>
<p>Find me in app/views/listitem/new.html.erb</p>