config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
    root "home#index"
    get '/user/subcategory/:id', to: "home#subcategory"
    get '/user/products/:id', to: "home#product"
    get '/user/cart/:id',to:"home#cart"
    post '/addcart',to:"home#addcart"
    get '/profile',to:"home#profile"
  
  namespace :supplier do
    resources :products
    resources :category
  end
 
  namespace :admins do
    get 'order/index'
    resources :users
    resources :order
    resources :categorylists
    resources :subcategories
  end

get 'listitem/new'
get 'listitem/index'
post 'listitems' ,to: "listitem#create"
post 'listitems/:id/inc' ,to: "listitem#add_quantity", as: "listitem_inc"
post 'listitems/:id/dec' ,to: "listitem#reduce_quantity", as: "listitem_dec"
delete 'listitems/:id' ,to: "listitem#destroy",as:"listitem_rem"


get '/carts/' ,to: "cart#show", as: "cart"
delete '/carts/:id' ,to: "cart#destroy" ,as: "cart_destroy"
resources :carts
# resources :products
resources :order
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products ,dependent: :delete_all
  has_many :list_items ,dependent: :delete_all
  has_many :products ,through: :list_items,dependent: :delete_all

  def sub_total
    sum=0
    self.list_items.each do |i|
      sum+= i.total_price
    end
    return sum
  end
  def sub_total1
    sum=[]
    j=1
    k=0
    self.list_items.each do |i|
      while(k<j)
        sum[k]= i.total_price
        k+=1
      end
      j+=1
    end
    return sum
  end
end

app/models/categorylist.rb
class Categorylist < ApplicationRecord
     mount_uploader :cover, CoverUploader
     has_many :subcategories, class_name: "Categorylist",foreign_key: "category_id",dependent: :destroy
     belongs_to :category, class_name: "Categorylist", optional: true
     has_many :products ,dependent: :delete_all
     validates :name, presence: true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :imageble,polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :cover, CoverUploader
    has_many :list_items ,dependent: :delete_all
    belongs_to :categorylist
    
    validates :name, presence: true
    validates :detail, presence: true
    validates :price, presence: true ,numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :cover, CoverUploader
  has_many :list_items ,dependent: :delete_all
  has_one :cart ,dependent: :destroy
  has_many :orders ,dependent: :delete_all
end

app/controllers/admins/categorylists_controller.rb
class Admins::CategorylistsController < ApplicationController  
  include Admin::CategoryHelper
  before_action :user_type, only: [:index,:show,:new,:create,:edit,:update,:destroy]
  
  
  def index
    @categories = Categorylist.all
    @users = User.all
  end

  def show
    $category_id = params[:id]
    @subcategories  = categorylist(params[:id]).subcategories
  end

  def new
    @category = Categorylist.new
  end

  def create
    @category = Categorylist.new(name: params['categorylist']['name'],cover:params['categorylist']['cover'])
    if @category.save
      flash[:notice] = "Category Created Sucessfully"
      redirect_to admins_categorylists_path 
    else
      render :new
    end
  end

  def edit
    @category = categorylist(params[:id])
  end

  def update
    @category = categorylist(params[:id])
    @category.update(name: params['categorylist']['name'],cover:params['categorylist']['cover'])
    if @category.save 
        flash[:notice] = "Category Updated Sucessfully"
        redirect_to admins_categorylists_path
      else
        render :edit
      end
    end

  def destroy
    categorylist(params[:id]).destroy
    flash[:notice] = "Category Deleted Sucessfully"

    redirect_to admins_categorylists_url
  end

  # private
  # def category_params
  #   params.require(:category).permit(:name)
  # end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include UserHelper
  def show
    @cart = find_user(current_user.id).cart
  end

  def destroy
    Cart.find(params[:id]).destroy
    redirect_to carts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UserHelper
  

  def index
    case
    when current_user.user_type =="user"
       @categories = Categorylist.all
       @product1 = Product.all
       sub1(@categories)
       
    when current_user.user_type =="admin"
      redirect_to "/admins/categorylists"
    when current_user.user_type =="supplier"
      redirect_to "/supplier/products"
    
      
    end
  end

  def subcategory
    @subcategory  = categorylist(params[:id]).subcategories
  end

  def product 
    @product  = categorylist(params[:id]).products
  end

  def profile
    @user = User.find(current_user.id)
  end

  def addcart

    @Addcart = ListItem.new
    @Addcart.save
    redirect_to root_url
  
  end

  def cart
    @CartItems = find_user(params[:id]).carts
    @CartItems.each do |cartItem|  
      @listitem = find_cart(cartItem.id).list_items
    end
  end

  
end

app/controllers/listitem_controller.rb
class ListitemController < ApplicationController
  include UserHelper
  before_action :listitem , only: [:add_quantity,:reduce_quantity,:destroy]
  
  def listitem
    ListItem.find(params[:id])
  end

  def create
    chosen_product = Product.find(params[:product_id])
    if find_user(current_user.id).cart == nil
      current_cart = Cart.create(user_id:current_user.id)

    else  
      current_cart =  find_user(current_user.id).cart
    end
    
    if find_cart(current_cart.id).products.include?(chosen_product)
      @list_item = find_cart(current_cart.id).list_items.find_by(product_id: chosen_product)
      @list_item.quantity += 1
    else
      @list_item = ListItem.new(cart_id:current_cart.id, product_id:chosen_product.id, user_id:current_user.id)
    end
    
    @list_item.save
    redirect_to cart_path
  end


  def add_quantity
    @list_item =  listitem
    @list_item.quantity += 1
    @list_item.save
    redirect_to cart_path
  end
  

  def reduce_quantity
    @list_item = listitem
    if @list_item.quantity > 1
      @list_item.quantity -= 1
    end
    @list_item.save
    redirect_to cart_path
  end
  def destroy
    @list_item = listitem
    @list_item.destroy
    redirect_to cart_path
  end 
  # private
  #   def list_item_params
  #     params.require(:list_item).permit(:quantity,:product_id, :cart_id)
  #   end

  
  
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  include UserHelper
  def index
    @products = []
    i=0
    n=1
    @orders = find_user(current_user.id).orders
        @orders.each do |order|
      while(i<n)
        @products[i] = Product.find(order.product_id)
        i+=1
      end
      n+=1
    end
  end


  def show
    @order = find_user(params[:id]).orders
  end

  def new
    @order = Order.new
  end

  def create
    current_cart =  find_user(current_user.id).cart
    find_cart(current_cart.id).products.each do |item|
        @order = Order.new(status:params["status"],user_id:current_user.id,product_id:item.id)
        @order.save
        
      end
      find_cart(current_cart.id).destroy
    
    redirect_to root_path
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listitem_helper.rb
module ListitemHelper
    
    def listitem
        ListItem.find(params[:id])
    end

    def user_find
        User.find(current_user.id)
    end
    
    def cart_find
        Cart.find(current_cart.id)
    end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/user_helper.rb
module UserHelper

    def find_user(arg)
        User.find(arg)
    end

    def find_cart(arg)
        Cart.find(arg)
    end

    def categorylist(arg)
        Categorylist.find(arg)
    end

    def sub1(arg)
      j=0
      k=1 
      @subcategory = []
      arg.each do |i|
        if i.category_id != nil
          while(j<k)
            @subcategory[j] = i  
            j+=1
          end
          k+=1
        end
      end
    end
end

app/views/admins/categorylists/_form.html.erb
<%= form_for([:admins, @category]) do |form| %>
  <div class="form-outline mb-4">
    <%= form.label :name %><br>
    <%= form.text_field :name ,class: "form-control "  %>
  </div>
   <div class="form-outline mb-4">
      <%= form.label :image %>
      <%= form.file_field :cover %>
   </div>
  <div>
    <%=  form.submit :save, class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/admins/categorylists/edit.html.erb
<div class="container">

<h1>Edit Your Details</h1>
<%= render 'form' %>

app/views/admins/categorylists/index.html.erb
<div class="container">
  <% flash.each do |type,msg| %>
    <div class="alert alert-success">
      <%=msg %>
    </div>
    <% end %>
      <%=link_to 'create', new_admins_categorylist_path, class: 'btn btn-dark' %>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">s.no</th>
              <th scope="col">Category</th>
              <th scope="col">Add</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <% if category.category_id==nil %>
                  <th scope="row">
                    <%=category.id %>
                  </th>
                  <td>
                    <%=link_to category.name ,admins_categorylist_path(category.id) %>
                  </td>
                  <td>
                    <%=link_to 'Edit', edit_admins_categorylist_path(category.id),class: "btn btn-primary"%>
                  </td>
                  <td>
                    <%=link_to 'Delete', admins_categorylist_path(category.id),class: "btn btn-danger" ,:method=> :delete, :confirm => 'Are you sure?' %></td>
              </tr>
              <% end %>
                <% end %>
          </tbody>
        </table>
</div>
<div class="container mb-5">
  <div class="container-fluid jumb1">
    <h1>Users</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">s.no</th>
          <th scope="col">User Name</th>
          <th scope="col">Email</th>
          <th scope="col">Pincode</th>
          <th scope="col">User Type</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row">
              <%=user.id %>
            </th>
            <td>
              <%=user.user_name %>
            </td>
            <td>
              <%=user.email %>
            </td>
            <td>
              <%=user.pincode %>
            </td>
            <td>
              <%=user.user_type %>
            </td>
            <% if user.user_type=="admin" %>
              <td></td>
              <% else %>
                <td>
                  <%=link_to 'Delete', admins_user_path(user.id), :method=> :delete, :confirm => 'Are you sure?' %></td>
                <% end %>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/categorylists/new.html.erb
<div class="container">
<h1>New category</h1>
<%= render 'form' %>
</div>

app/views/admins/categorylists/show.html.erb
<div class="container">

<%= link_to 'create subcategory', new_admins_subcategory_path, class: 'btn btn-dark' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">s.no</th>
      <th scope="col">Category</th>
      <th scope="col">Add</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
   <% @subcategories.each do |subcategory| %>
    <tr>
      <th scope="row"><%= subcategory.id %></th>
      <td><%=  subcategory.name %></td>
      <td><%= link_to 'Edit', edit_admins_subcategory_path(subcategory.id),class:"btn btn-primary"%></td>
     <td><%= link_to 'Delete', admins_subcategory_path(subcategory.id),class:"btn btn-danger" ,:method => :delete,data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>