config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
    root "home#index"
    get '/user/subcategory/:id', to: "home#subcategory"
    get '/user/products/:id', to: "home#product"
    get '/user/cart/:id',to:"home#cart"
    post '/addcart',to:"home#addcart"
    get '/profile',to:"home#profile"
  
  namespace :supplier do
    resources :products
    resources :category
  end
 
  namespace :admins do
    get 'order/index'
    resources :users
    resources :order
    resources :categorylists
    resources :subcategories
  end

get 'listitem/new'
get 'listitem/index'
post 'listitems' ,to: "listitem#create"
post 'listitems/:id/inc' ,to: "listitem#add_quantity", as: "listitem_inc"
post 'listitems/:id/dec' ,to: "listitem#reduce_quantity", as: "listitem_dec"
delete 'listitems/:id' ,to: "listitem#destroy",as:"listitem_rem"


get '/carts/' ,to: "cart#show", as: "cart"
delete '/carts/:id' ,to: "cart#destroy" ,as: "cart_destroy"
resources :carts
# resources :products
resources :order
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products ,dependent: :delete_all
  has_many :list_items ,dependent: :delete_all
  has_many :products ,through: :list_items,dependent: :delete_all

  def sub_total
    sum=0
    self.list_items.each do |i|
      sum+= i.total_price
    end
    return sum
  end
  def sub_total1
    sum=[]
    j=1
    k=0
    self.list_items.each do |i|
      while(k<j)
        sum[k]= i.total_price
        k+=1
      end
      j+=1
    end
    return sum
  end
end

app/models/categorylist.rb
class Categorylist < ApplicationRecord
     mount_uploader :cover, CoverUploader
     has_many :subcategories, class_name: "Categorylist",foreign_key: "category_id",dependent: :destroy
     belongs_to :category, class_name: "Categorylist", optional: true
     has_many :products ,dependent: :delete_all
     validates :name, presence: true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :imageble,polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :cover, CoverUploader
    has_many :list_items ,dependent: :delete_all
    belongs_to :categorylist
    
    validates :name, presence: true
    validates :detail, presence: true
    validates :price, presence: true ,numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :cover, CoverUploader
  has_many :list_items ,dependent: :delete_all
  has_one :cart ,dependent: :destroy
  has_many :orders ,dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
  
    protected
    
      def configure_permitted_parameters
        # devise_parameter_sanitizer.permit(:sign_in, keys: [:user_name,:password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:user_name,:user_type,:phone,:pincode,:city,:address,:email])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name,:user_name,:phone,:pincode,:city,:address,:email,:cover]) 
      end
 

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include UserHelper
  def show
    @cart = find_user(current_user.id).cart
  end

  def destroy
    Cart.find(params[:id]).destroy
    redirect_to carts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UserHelper
  

  def index
    case
    when current_user.user_type =="user"
       @categories = Categorylist.all
       @product1 = Product.all
       sub1(@categories)
       
    when current_user.user_type =="admin"
      redirect_to "/admins/categorylists"
    when current_user.user_type =="supplier"
      redirect_to "/supplier/products"
    
      
    end
  end

  def subcategory
    @subcategory  = categorylist(params[:id]).subcategories
  end

  def product 
    @product  = categorylist(params[:id]).products
  end

  def profile
    @user = User.find(current_user.id)
  end

  def addcart

    @Addcart = ListItem.new
    @Addcart.save
    redirect_to root_url
  
  end

  def cart
    @CartItems = find_user(params[:id]).carts
    @CartItems.each do |cartItem|  
      @listitem = find_cart(cartItem.id).list_items
    end
  end

  
end

app/controllers/listitem_controller.rb
class ListitemController < ApplicationController
  include UserHelper
  before_action :listitem , only: [:add_quantity,:reduce_quantity,:destroy]
  
  def listitem
    ListItem.find(params[:id])
  end

  def create
    chosen_product = Product.find(params[:product_id])
    if find_user(current_user.id).cart == nil
      current_cart = Cart.create(user_id:current_user.id)

    else  
      current_cart =  find_user(current_user.id).cart
    end
    
    if find_cart(current_cart.id).products.include?(chosen_product)
      @list_item = find_cart(current_cart.id).list_items.find_by(product_id: chosen_product)
      @list_item.quantity += 1
    else
      @list_item = ListItem.new(cart_id:current_cart.id, product_id:chosen_product.id, user_id:current_user.id)
    end
    
    @list_item.save
    redirect_to cart_path
  end


  def add_quantity
    @list_item =  listitem
    @list_item.quantity += 1
    @list_item.save
    redirect_to cart_path
  end
  

  def reduce_quantity
    @list_item = listitem
    if @list_item.quantity > 1
      @list_item.quantity -= 1
    end
    @list_item.save
    redirect_to cart_path
  end
  def destroy
    @list_item = listitem
    @list_item.destroy
    redirect_to cart_path
  end 
  # private
  #   def list_item_params
  #     params.require(:list_item).permit(:quantity,:product_id, :cart_id)
  #   end

  
  
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  include UserHelper
  def index
    @products = []
    i=0
    n=1
    @orders = find_user(current_user.id).orders
        @orders.each do |order|
      while(i<n)
        @products[i] = Product.find(order.product_id)
        i+=1
      end
      n+=1
    end
  end


  def show
    @order = find_user(params[:id]).orders
  end

  def new
    @order = Order.new
  end

  def create
    current_cart =  find_user(current_user.id).cart
    find_cart(current_cart.id).products.each do |item|
        @order = Order.new(status:params["status"],user_id:current_user.id,product_id:item.id)
        @order.save
        
      end
      find_cart(current_cart.id).destroy
    
    redirect_to root_path
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listitem_helper.rb
module ListitemHelper
    
    def listitem
        ListItem.find(params[:id])
    end

    def user_find
        User.find(current_user.id)
    end
    
    def cart_find
        Cart.find(current_cart.id)
    end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/user_helper.rb
module UserHelper

    def find_user(arg)
        User.find(arg)
    end

    def find_cart(arg)
        Cart.find(arg)
    end

    def categorylist(arg)
        Categorylist.find(arg)
    end

    def sub1(arg)
      j=0
      k=1 
      @subcategory = []
      arg.each do |i|
        if i.category_id != nil
          while(j<k)
            @subcategory[j] = i  
            j+=1
          end
          k+=1
        end
      end
    end
end

app/views/home/index.html.erb
<div class="container">
<div class="btn-group">
<% @categories.each do |category| %>
     <% if category.category_id==nil %>

  <a class="btn btn-sm dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">

  <% if category.cover_url %>
    <%=image_tag(category.cover_url,height: 100,width: 100)%><br>
  <%else %>
        <%=image_tag "demo.png", height: 100,width: 100 %><br>
  <% end %>
    <%= category.name%>
  </a>
  <ul class="dropdown-menu">
    <% @subcategory.each do |sub1|%>
        <%if sub1.category_id == category.id%>
    <li><a class="dropdown-item" href="/user/products/<%=sub1.id%>"><%= sub1.name%></a></li>
            
        <%end%>
        <%end%>
  </ul>
  <%end%>
<% end %>
</div>
</div>

<div class="container-fluid mb-5 bg-light">
    <div class="container d-flex align-content-between flex-wrap  mt-5 bg-white">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <%=image_tag "slider.jpg", height: 200,class: "d-block "%>
                </div>
                <div class="carousel-item">
                    <%=image_tag "slider1.jpg", height: 200,class: "d-block "%>
                </div>
                <div class="carousel-item">
                    <%=image_tag "slider2.jpg", height: 200,class: "d-block "%>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>




    <div class="jumbotron-fluid jumb1">
        <h1>Category</h1>

        <div class="container-fluid jumb1">
            <div class="container flex-item3 ">
                <% @categories.each do |category| %>
                    <% if category.category_id==nil %>
                        <div class="gy-4 mt-2 my-5">
                            <div class="icon-box">
                                <a class="link1" href="/user/subcategory/<%=category.id%>">
                                    <% if category.cover_url %>
                                        <%=image_tag(category.cover_url,height: 100,width: 100)%>
                                    <%else %>
                                          <%=image_tag "demo.png", height: 100,width: 100 %>
                                    <% end %>
                                          <p>
                                             <%=category.name %>
                                          </p>
                                </a>
                            </div>
                        </div>
                        <%end%>
                <% end %>
            </div>
        </div>

         <div class="container-fluid mt-5 mb-5 ">
            <div class="card-group">
                <div class="card m-3">
                    <%=image_tag "slider3.jpg", height: 200,class: "d-block "%>
                </div>

                <div class="card m-3">
                    <%=image_tag "slider4.jpg", height: 200,class: "d-block "%>
                </div>

                <div class="card m-3">
                    <%=image_tag "slider5.jpg", height: 200,class: "d-block "%>
                </div>
            </div>
        </div>


        <div class="container-fluid mb-5 p-2 border border-1 border-dark">

            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active d-flex justify-content-around">
                        <%@product1.each do |product|%>
                            <div class="" style="width: 18rem;">
                                    <% if product.cover_url %>
                                <%=image_tag(product.cover.url,class: "card-img-top" , height: 150, width: 150)%>
                                        
                                    <%else %>
                                          <%=image_tag "demo.png", height: 100,width: 100 %>
                                    <% end %>



                                    <div class="card-body text-center">
                                        <h5 class="card-title"><%=product.name%></h5>
                                         
                                        <p class="card-text">
                                            <%=number_to_currency(product.price)%></p>
                                        <%=button_to "cart", listitems_path(product_id: product.id),:class=>"btn btn-primary" %>
                                    </div>
                            </div>
                            <% end %>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="container">
            <%=image_tag "slider6.jpg", height: 200,class: "d-block "%>
        </div>
     

    </div>

app/views/home/login.html.erb
<section class="vh-100 bg-primary" >
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-5-strong">
          <div class="card-body p-5 text-center">
            <h3 class="mb-5">Sign In</h3>
            <div class="form-outline mb-4">
              <input type="email" placeholder="Enter your Email" id="typeEmailX-2" class="form-control form-control-lg" />
            </div>
            <div class="form-outline mb-4">
              <input type="password" placeholder="Enter your Password" id="typePasswordX-2" class="form-control form-control-lg" />  
            </div>
            <button class="btn btn-primary " type="submit">Login</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/product.html.erb
<div class="jumbotron-fluid jumb1">
    <h1>Products</h1>
      <div class="container-fluid jumb1">
        <div class="container flex-item3 ">
               <% @product.each do |product| %>
               <div class="card" style="width: 20rem;">
                  <%= image_tag(product.cover.url,class:"card-img-top" , height: 150, width: 150) if product.cover%>
                      <div class="card-body">
                        <h5 class="card-title">Name : <%= product.name %></h5>
                        <h5 class="card-title">Price : <%= number_to_currency(product.price) %></h5>
                        <p class="card-text">Detail :<%= product.detail%></p>
                        <%= button_to "cart", listitems_path(product_id: product.id),:class=>"btn btn-primary" %>
                      </div>
                </div>
                <% end  %>
        </div>
   </div>
</div>

app/views/home/profile.html.erb
<section class="vh-100" style="background-color: #f4f5f7;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 bg-primary text-center text-white" style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">            
                <% if @user.cover_url %>
                    <%= image_tag(@user.cover_url,width: 80,class:"img-fluid my-5")%>
                <%else %>
                    <%=image_tag "xyz.png", width: 80,class:"img-fluid my-5" %><br>
                <% end %>
              <h5><%=@user.user_name%></h5>
              <p><%=@user.first_name%> <%=@user.last_name%></p>
                  <i class="bi bi-facebook "></i>
                  <i class="bi bi-twitter m-4"></i>
                  <i class="bi bi-instagram"></i>
                  <h5><%= link_to "Edit Profile" ,edit_user_registration_path(),class:"text-white"%></h5>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h3>Information</h3>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h5>Email</h5>
                    <p class="text-muted"><%=@user.email%></p>
                  </div>
                  <div class="col-6 mb-3">
                    <h5>Phone</h5>
                    <p class="text-muted"><%=@user.phone%></p>
                  </div>
                </div>
                <h3>Contact</h3>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h5>Address</h5>
                    <p class="text-muted"><%=@user.address%></p>
                  </div>
                  <div class="col-6 mb-3">
                    <h5>City</h5>
                    <p class="text-muted"><%=@user.city%></p>
                  </div>
                  <div class="col-6 mb-3">
                    <h5>Pincode</h5>
                    <p class="text-muted"><%=@user.pincode%></p>
                  </div>
                </div>
               
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/register.html.erb
<section class="vh-100 bg-primary" >
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

                <%= form_with model: @user do |form| %>
                <div class="form-outline mb-4">
                     <%=  form.text_field :title,{placeholder:"First Name"  ,class:"form-control form-control-lg"} %>
                </div>
                <div class="form-outline mb-4">
                    <%=  form.text_field :title ,{placeholder:"First Name"  ,class:"form-control form-control-lg"} %>
                </div>
                <div class="form-outline mb-4">
                    <%=  form.text_field :title ,{placeholder:"Last Name"  ,class:"form-control form-control-lg"} %>
                </div>
                <div class="form-outline mb-4">
                  <%=  form.text_field :title ,{placeholder:"User Name"  ,class:"form-control form-control-lg"} %>
                </div>
                
                <div class="form-outline mb-4">
                  <%= form.email_field :title,{placeholder:"Email" ,class:"form-control form-control-lg"} %>
                </div>
                <%# 
                <div class="form-outline mb-4">
                  <%= form.number_field :title,{placeholder:"Phone" ,class:"form-control form-control-lg"} %>
                <%#</div>
                 %>
                <div class="form-outline mb-4">
                  <%= form.number_field :title,{placeholder:"Pincode" ,class:"form-control form-control-lg"} %>
                </div>
                
                <select class="form-select  form-select-lg mb-4" aria-label="Default select example">
                        <option selected>Select User Type</option>
                        <option value="1">User</option>
                        <option value="2">Supplier</option>
                </select>
                <div class="form-outline mb-4">
                  <%=  form.password_field :title ,{placeholder:"Password"  ,class:"form-control form-control-lg"} %>
                </div>

                <div class="form-outline mb-4">
                  <%=  form.password_field :title ,{placeholder:"Confirm Password"  ,class:"form-control form-control-lg"} %>
                </div>


                <div class="d-flex justify-content-center">
                  <%= form.submit "Register", {class:"btn btn-success"}%>
                </div>

                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="login" class="fw-bold text-body"><u>Login here</u></a></p>
                <% end %>
            

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/subcategory.html.erb
 <div class="jumbotron-fluid jumb1">
  <h1>Sub Category</h1>
  <div class="container-fluid jumb1">
    <div class="container flex-item3 ">
      <% @subcategory.each do |subcategory| %>
        <div class="gy-4 mt-2 my-5">
          <div class="icon-box">
            <a class="link1" href="/user/products/<%=subcategory.id%>">
              <% if subcategory.cover_url %>
                 <%=image_tag(subcategory.cover_url,height: 100,width: 100)%>
               <% else %>
                 <%=image_tag "demo.png", height: 100,width: 100 %>
               <% end %>
                  <p>
                     <%=subcategory.name %>
                  </p>
            </a>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>