config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
    root "home#index"
    get '/user/subcategory/:id', to: "home#subcategory"
    get '/user/products/:id', to: "home#product"
    get '/user/cart/:id',to:"home#cart"
    post '/addcart',to:"home#addcart"
    get '/profile',to:"home#profile"
  
  namespace :supplier do
    resources :products
    resources :category
  end
 
  namespace :admins do
    get 'order/index'
    resources :users
    resources :order
    resources :categorylists
    resources :subcategories
  end

get 'listitem/new'
get 'listitem/index'
post 'listitems' ,to: "listitem#create"
post 'listitems/:id/inc' ,to: "listitem#add_quantity", as: "listitem_inc"
post 'listitems/:id/dec' ,to: "listitem#reduce_quantity", as: "listitem_dec"
delete 'listitems/:id' ,to: "listitem#destroy",as:"listitem_rem"


get '/carts/' ,to: "cart#show", as: "cart"
delete '/carts/:id' ,to: "cart#destroy" ,as: "cart_destroy"
resources :carts
# resources :products
resources :order
 
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :cover, CoverUploader
    has_many :list_items ,dependent: :delete_all
    belongs_to :categorylist
    
    validates :name, presence: true
    validates :detail, presence: true
    validates :price, presence: true ,numericality: true
end

app/controllers/supplier/category_controller.rb
class Supplier::CategoryController < ApplicationController
  include Supplier::CategoryHelper
  before_action :user_type, only: [:index,:show]


  def index
    @category = Categorylist.all
  end
  def show
    @subcategory  = Categorylist.find(params[:id]).subcategories
  end
end

app/controllers/supplier/products_controller.rb
class Supplier::ProductsController < ApplicationController
  
  include Supplier::CategoryHelper
  before_action :user_type, only: [:index,:show,:new,:create,:edit,:update,:destroy]
  
  def index
    @product = Product.all
    @category = Categorylist.all
  end
 

  def new
    @product = Product.new
  end


  def create
    params[:product][:categorylist_id] = $categorylist_id
    @product = Product.new(product_params)
    if @product.save
      redirect_to supplier_products_url
    else
      render :new
    end
  end

  def edit
    @product = product_find(params[:id])
  end


  def update
    @product = product_find(params[:id])
      @product.update(product_params)
      if @product.save  
        redirect_to supplier_products_url
      else
        render :edit
      end
    end


  def destroy
    product_find(params[:id]).destroy
    redirect_to supplier_products_url
  end

  private
  def product_params
    params.require(:product).permit(:name, :detail, :price ,:categorylist_id,:cover)
  end
end

app/controllers/supplier/supplier_controller.rb
class SupplierController < ApplicationController
  def index
    
  end
end

app/helpers/supplier/category_helper.rb
module Supplier::CategoryHelper

    def user_type  
        if current_user.user_type == "supplier"
        else
          redirect_to root_url
        end
      end

    def product_find(arg)
      Product.find(arg)
    end
      
end

app/helpers/supplier/product_helper.rb
module Supplier::ProductHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/views/supplier/products/_form.html.erb
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-5-strong">
          <div class="card-body p-5 ">
             <%=  form_for([:supplier,@product])do |form| %>
                <div class="form-outline mb-4">
                  <%= form.label :name %><br>
                  <%= form.text_field :name ,class: "form-control form-control-lg"  %>
                </div>
                <div class="form-outline mb-4">
                  <%= form.label :detail %><br>
                  <%= form.text_field :detail ,class: "form-control form-control-lg"  %>
                </div>
                <div class="form-outline mb-4">
                  <%= form.label :price %><br>
                  <%= form.text_field :price,class: "form-control form-control-lg"  %>
                </div>
                <div class="form-outline mb-4">
                  <%= form.label :Image %>
                  <%= form.file_field :cover %>
                </div>
                  <%= form.hidden_field( :categorylist_id)  %>
                <div>
                  <%= form.submit class:"btn btn-primary"%>
                </div>
              <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

app/views/supplier/products/edit.html.erb
<h3 class="mb-5 text-center">Edit Product</h3>
<%= render 'form'%>
      

app/views/supplier/products/index.html.erb
<div class="jumbotron-fluid jumb1">
         <h1>Category</h1>
         <div class="container-fluid jumb1">
            <div class="container flex-item3 ">
                     <% @category.each do |category| %>
                     <% if category.category_id == nil %>
                        <div class="gy-4 mt-2 my-5">
                           <div class="icon-box">
                              <a class="link1" href="/supplier/category/<%=category.id%>">
                              
                               <% if category.cover_url %>
                                    <%= image_tag(category.cover_url,height: 100,width: 100)%>
                              <%else %>
                                    <%= image_tag "demo.png", height: 100,width: 100 %>
                              <% end %>
                              <p><%= category.name %></p>    
                              </a>
                           </div>
                        </div>
                        <%end%>
                     <% end  %>
            </div>
            <h1>Products</h1>
         <div class="container-fluid jumb1">
            <div class="container flex-item3 ">
                 <table class="table">
                  <thead>
                     <tr>
                        <th scope="col">s.no</th>
                        <th scope="col">Name</th>
                        <th scope="col">Detail</th>
                        <th scope="col">Price</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                     </tr>
                  </thead>
                  <tbody>
                  

                     <% @product.each do |product| %>
                     
                     <tr>
                        <th scope="row"><%=product.id%></th>
                        <td><%=product.name%></td>
                        <td><%=product.detail%></td>
                        <td><%=number_to_currency(product.price)%></td>
                        <td><%= link_to 'Edit', edit_supplier_product_path(product.id)  %></td>
                        <td><%= link_to 'Delete', supplier_product_path(product.id), :method => :delete, :confirm => 'Are you sure?' %></td>
                                                         
                     </tr>
                     <% end  %>
                  </tbody>
                  </table>
            </div>
         </div>

</div>

app/views/supplier/products/new.html.erb
<h3 class="mb-5 text-center">Add Product</h3>
<%= render 'form'%>